config/routes.rb
Rails.application.routes.draw do
  devise_for :users



  root to: "home#top"

   authenticated :user do
   root 'users#show', as: :user_root
  end

  devise_scope :user do
  # 未認証のユーザーがアクセスできるルートを定義
  get '/unauthenticated', to: 'unauthenticated#action'
end
  resources :books, only: [:new, :index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :edit, :index, :update]
  get 'home/about' , as: :about
  get '/' =>'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <script src="https://kit.fontawesome.com/92bef9f57d.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
          <span>Bookers</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">


    <% if user_signed_in? %>
      <li>
          <a class="nav-link" href="<%=url_for(user_path(current_user) )%>">
          <div class="svg">
          <i class="fa-solid fa-house"></i>
          </div>
          Home
        </a>
      </li>
      <li>
          <a class="nav-link" href="<%=url_for(users_path)%>">
          <div class="svg">
          <i class="fa-solid fa-users"></i>
          </div>
          Users
        </a>
      </li>
      <li>
          <a class="nav-link" href="<%=url_for(books_path)%>">
          <div class="svg">
          <i class="fa-solid fa-book-open"></i>
          </div>
          Books
        </a>
      </li>
      <li>
          <a class="nav-link" href="<%= destroy_user_session_path %>" data-method="delete">
          <div class="svg">
          <i class="fa-solid fa-right-from-bracket"></i>
          </div>
          Log out
        </a>
      </li>
    <% else %>
      <li>
          <a class="nav-link" href="/">
          <div class="svg">
          <i class="fa-solid fa-house"></i>
          </div>
          Home
        </a>
      </li>
      <li>
          <a class="nav-link" href="<%= about_path %>">
          <div class="svg">
          <i class="fa-solid fa-link"></i>
          </div>
          About
        </a>
      </li>
      <li>
        <a class="nav-link" href="<%= new_user_registration_path %>">
          <div class="svg">
          <i class="fa-solid fa-user-plus"></i>
          </div>
          Sign up
        </a>
      </li>
      <li>
        <a class="nav-link" href="<%= new_user_session_path %>">
          <div class="svg">
          <i class="fa-solid fa-right-to-bracket"></i>
          </div>
          Log in
        </a>
      </li>
    <% end %>
    </ul>
    </div>

      </div>
    </nav>
  </header>
  <main>

    <%= yield %>
    </main>
  </body>



  <footer>
  <div class="container mt-5">
  	<div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

</html>